### ISSUE TITLE
Is it possible to disable this for certain files?

### ISSUE THREAD

**Issue by bbakersmith** [tpope/vim-classpath#10]
This runs when git pops open vim for commit messages in a clojure project directory, and it is pretty slow. I would like to exclude it for commit messages at least.

**Comment by tpope** [comment]
Are you sure it's this plugin? It runs on [four filetypes only](https://github.com/tpope/vim-classpath/blob/1ef18a10512fe0f84bb2c412b38e613c331a7b55/plugin/classpath.vim#L11), and `gitcommit` ain't one of them.

**Comment by bbakersmith** [comment]
Ah, I'm sorry for the noise, this is actually an issue with vim-salve.
