### ISSUE TITLE
vim-classpath should keep manually set path from vimrc.

### ISSUE THREAD

**Issue by mtbrooks33** [tpope/vim-classpath#9]
I manually set `path=$PWD/**` in my `.vimrc` to ensure that `:find` works as I expect it to. With vim-classpath, navigating to another file resets my `path` and `:find` does not work as expected. 

For example, opening vim in my project root without specifying a file allows me to `:find somef<Tab>` just fine. However, opening any file in my project changes the `path`, so calling `:find anoth<Tab>` does not list all of the files that it should (all of the files in the path `$PWD/**`.

**Comment by tpope** [comment]
Given that's classpath.vim's only feature, why do you have it installed? (If you installed it for fireplace.vim, it's much less necessary than it used to be, and you can probably remove it.)

**Comment by mtbrooks33** [comment]
I installed it for fireplace.vim. Thank you for the suggestion.
